version: '3.9'

services:
  rustapi:
    container_name: rustapi
    image: rustapi:1.0.0
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@rustapi_db:5432/postgres
    ports:
      - '8000:8000'
    depends_on:
      - rustapi_db
  
  rustapi_db: 
    container_name: rustapi_db
    image: postgres:12
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}